// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("UseCaseMaker")>]
[<assembly: AssemblyProductAttribute("UseCaseMaker")>]
[<assembly: AssemblyDescriptionAttribute("C.A.S.E. tool that helps software developers to write organized use cases and to maintain related requirements")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "UseCaseMaker"
    let [<Literal>] AssemblyProduct = "UseCaseMaker"
    let [<Literal>] AssemblyDescription = "C.A.S.E. tool that helps software developers to write organized use cases and to maintain related requirements"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
