// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("UseCaseMakerApp")]
[assembly: AssemblyProductAttribute("UseCaseMaker")]
[assembly: AssemblyDescriptionAttribute("C.A.S.E. tool that helps software developers to write organized use cases and to maintain related requirements")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "UseCaseMakerApp";
        internal const System.String AssemblyProduct = "UseCaseMaker";
        internal const System.String AssemblyDescription = "C.A.S.E. tool that helps software developers to write organized use cases and to maintain related requirements";
        internal const System.String AssemblyVersion = "1.0";
        internal const System.String AssemblyFileVersion = "1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
